// データソース:
// 「抗血栓療法中の区域麻酔・神経ブロックガイドライン 改訂第2版」
// 日本ペインクリニック学会・日本麻酔科学会・日本区域麻酔学会 合同
// 2026年 表8（ブロック分類）・表9（休薬期間）・表11（DOAC用量分類）

export const DEEP_BLOCKS = [
  // 頭頸部
  "頸部硬膜外麻酔",
  "頸部神経根ブロック",
  "頸椎椎間関節ブロック（後内側枝ブロックを含む）",
  "深頸神経叢ブロック",
  "星状神経節ブロック（SGB）",
  "三叉神経節ブロック",
  "上顎神経ブロック",
  "下顎神経ブロック",
  "翼口蓋神経節ブロック",
  "舌咽神経ブロック",
  // 上肢
  "腕神経叢ブロック（斜角筋間/鎖骨下アプローチ）",
  // 胸部
  "胸部硬膜外麻酔",
  "胸部傍脊椎ブロック",
  "胸椎神経根ブロック",
  "胸部交感神経節ブロック",
  // 腰部
  "脊髄くも膜下麻酔",
  "腰部硬膜外麻酔",
  "腰部傍脊椎ブロック",
  "腰椎神経根ブロック",
  "腰部交感神経節ブロック",
  // 腹部・骨盤
  "腹腔神経叢（内臓神経）ブロック",
  // 下肢
  "仙骨硬膜外麻酔",
  "腰神経叢ブロック",
  "仙骨神経叢ブロック",
  "PENGブロック（pericapsular nerve group）",
  "坐骨神経ブロック（前方/傍仙骨アプローチ）",
];

export const SUPERFICIAL_BLOCKS = [
  // 頭頸部
  "浅頸神経叢ブロック",
  "後頭神経ブロック",
  "おとがい神経ブロック",
  "眼窩上神経ブロック",
  "眼窩下神経ブロック",
  // 上肢
  "腕神経叢ブロック（鎖骨上/腋窩アプローチ）",
  "肩甲上神経ブロック",
  "尺骨/正中/橈骨神経ブロック",
  // 胸部
  "肋間神経ブロック",
  "前鋸筋面ブロック（SAブロック）",
  "胸椎椎間関節ブロック（後内側枝ブロックを含む）",
  // 腰部
  "腰椎椎間関節ブロック（後内側枝ブロックを含む）",
  // 腹部・骨盤
  "腹直筋鞘ブロック",
  "腹横筋膜面ブロック（TAPブロックなど）",
  "腸骨鼠径・腸骨下腹神経ブロック",
  // 下肢
  "大腿神経ブロック",
  "閉鎖神経ブロック",
  "坐骨神経ブロック（臀下部/膝窩アプローチ）",
  "外側大腿皮神経ブロック",
  "伏在神経ブロック",
  "脛骨/腓腹神経ブロック",
  // 全身
  "関節内注射",
  "トリガーポイント注射",
];

export const DRUGS = [
  // ============ 抗血小板薬等 ============
  {
    id: "aspirin",
    category: "antiplatelet",
    name: "アスピリン（低用量 ＜200 mg/日）",
    brand: "バイアスピリン®ほか",
    mechanism: "トロンボキサンA2合成阻害（不可逆的）",
    halfLifeText: "約2時間（血小板寿命相当で効果持続）",
    washoutMid: {
      display: "休薬なし",
      hours: 0,
      note: "低用量アスピリン（＜200 mg/日）は神経ブロック前の休薬を必須としない。出血・血栓リスクを個別評価して対応する。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "—（休薬なし）", hours: 0 },
  },
  {
    id: "aspirin-high",
    category: "antiplatelet",
    name: "アスピリン（高用量 ≥200 mg/日）",
    brand: "アスピリン®ほか",
    mechanism: "トロンボキサンA2合成阻害（不可逆的）",
    halfLifeText: "約2時間（血小板寿命相当で効果持続）",
    washoutMid: {
      display: "3〜7日",
      days: 7,
      note: "高用量アスピリンでは出血リスクが用量依存性に高まるため、高リスク手技では3〜7日間の休薬を提案。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
  },
  {
    id: "diclofenac",
    category: "antiplatelet",
    name: "ジクロフェナク",
    brand: "ボルタレン®",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "1〜2時間",
    washoutMid: { display: "休薬必須でない（低用量アスピリンに準じる）", hours: 0 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "indomethacin",
    category: "antiplatelet",
    name: "インドメタシン",
    brand: "インダシン®",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "5〜10時間",
    washoutMid: { display: "休薬必須でない（低用量アスピリンに準じる）", hours: 0 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "ibuprofen",
    category: "antiplatelet",
    name: "イブプロフェン",
    brand: "ブルフェン®ほか",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "2〜4時間",
    washoutMid: { display: "休薬必須でない（低用量アスピリンに準じる）", hours: 0 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "flurbiprofen",
    category: "antiplatelet",
    name: "フルルビプロフェン",
    brand: "ロピオン®",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "6時間",
    washoutMid: { display: "休薬必須でない（低用量アスピリンに準じる）", hours: 0 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "celecoxib",
    category: "antiplatelet",
    name: "セレコキシブ",
    brand: "セレコックス®",
    mechanism: "COX-2選択的阻害",
    halfLifeText: "5〜9時間",
    washoutMid: {
      display: "休薬不要",
      days: 0,
      note: "血小板凝集を直接阻害する作用はないとされています。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "休薬の必要なし", hours: 0 },
  },
  {
    id: "clopidogrel",
    category: "antiplatelet",
    name: "クロピドグレル",
    brand: "プラビックス®",
    mechanism: "P2Y12受容体遮断（不可逆的）",
    halfLifeText: "0.5〜3時間（作用は血小板寿命相当で持続）",
    washoutMid: {
      display: "7日",
      days: 7,
      note: "脳梗塞・虚血性心疾患の二次予防目的では5日への短縮も許容される。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去直後より", hours: 0 },
  },
  {
    id: "ticlopidine",
    category: "antiplatelet",
    name: "チクロピジン",
    brand: "パナルジン®",
    mechanism: "アデニル酸シクラーゼ活性化＋P2Y12受容体遮断",
    halfLifeText: "1.5時間（作用は血小板寿命相当で持続）",
    washoutMid: {
      display: "7〜10日",
      days: 10,
      note: "状況により短縮も考慮されます。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "prasugrel",
    category: "antiplatelet",
    name: "プラスグレル",
    brand: "エフィエント®",
    mechanism: "P2Y12受容体遮断（不可逆的）",
    halfLifeText: "5時間（作用は血小板寿命相当で持続）",
    washoutMid: {
      display: "7日",
      days: 7,
      note: "脳梗塞・虚血性心疾患の二次予防目的では5日への短縮も許容される。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去24時間後より", hours: 24 },
  },
  {
    id: "ticagrelor",
    category: "antiplatelet",
    name: "チカグレロル",
    brand: "ブリリンタ®",
    mechanism: "P2Y12受容体遮断（可逆的）",
    halfLifeText: "6〜12時間（活性代謝物含む）",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "P2Y12受容体への結合が可逆的なためクロピドグレル・プラスグレルより短い5日間の休薬。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去24時間後より", hours: 24 },
  },
  {
    id: "cilostazol",
    category: "antiplatelet",
    name: "シロスタゾール",
    brand: "プレタール®",
    mechanism: "ホスホジエステラーゼ阻害",
    halfLifeText: "11〜13時間",
    washoutMid: {
      display: "休薬必須でない",
      hours: 0,
      note: "休薬を支持するエビデンスなし。出血リスクが高い場合は2日間を目安に休薬を考慮。アスピリンと併用中の場合はアスピリンの基準に従う。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "dipyridamole",
    category: "antiplatelet",
    name: "ジピリダモール",
    brand: "ペルサンチン®",
    mechanism: "ホスホジエステラーゼ阻害",
    halfLifeText: "10時間",
    washoutMid: {
      display: "休薬必須でない",
      hours: 0,
      note: "休薬を支持するエビデンスなし。出血リスクが高い場合は2日間を目安に休薬を考慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "epa",
    category: "antiplatelet",
    name: "イコサペント酸エチル",
    brand: "エパデール®",
    mechanism: "トロンボキサンA2阻害",
    halfLifeText: "60〜65時間",
    washoutMid: {
      display: "休薬必須でない",
      hours: 0,
      note: "休薬を支持するエビデンスなし。出血リスクが高い場合は7日間を目安に休薬を考慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "omega3-epa-dha",
    category: "antiplatelet",
    name: "オメガ-3脂肪酸エチル（EPA・DHA配合）",
    brand: "ロトリガ®",
    mechanism: "トロンボキサンA2産生抑制等による抗血小板作用（EPA＋DHA配合製剤）",
    halfLifeText: "EPA・DHAは血小板膜リン脂質に取り込まれ、効果は血小板の入れ替わる期間持続する",
    washoutMid: {
      display: "休薬必須でない（イコサペント酸エチルに準じる）",
      hours: 0,
      note: "ガイドライン本表に個別記載なし。イコサペント酸エチルに準じる。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
    generalNote:
      "ガイドライン本表に記載のない薬剤のため、エパデール®の基準を準用した参考値です。",
  },
  {
    id: "sarpogrelate",
    category: "antiplatelet",
    name: "サルポグレラート",
    brand: "アンプラーグ®",
    mechanism: "5-HT2受容体遮断",
    halfLifeText: "0.8時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "beraprost",
    category: "antiplatelet",
    name: "ベラプロスト",
    brand: "ドルナー®／プロサイリン®",
    mechanism: "アデニル酸シクラーゼ活性化",
    halfLifeText: "0.5〜0.7時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "limaprost",
    category: "antiplatelet",
    name: "リマプロストアルファデクス",
    brand: "オパルモン®／プロレナール®",
    mechanism: "プロスタグランジンE1誘導体。血小板cAMP増加による血小板凝集抑制",
    halfLifeText: "約0.5〜1時間",
    washoutMid: {
      display: "1日（ベラプロスト等に準じる）",
      days: 1,
      note: "ガイドライン本表に個別記載なし。同種同効薬に準じる。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
    generalNote:
      "ガイドライン本表に記載のない薬剤のため、同種同効薬の基準を準用した参考値です。",
  },
  {
    id: "clomipramine",
    category: "antiplatelet",
    name: "クロミプラミン",
    brand: "アナフラニール®",
    mechanism: "セロトニン再取り込み抑制（三環系）",
    halfLifeText: "24時間",
    washoutMid: {
      display: "休薬必須でない（休薬検討時は5日）",
      hours: 0,
      note: "一律の休薬を支持するエビデンスなし。休薬を検討する場合は5日間を目安とするが、精神症状悪化リスクに十分配慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "sertraline",
    category: "antiplatelet",
    name: "セルトラリン",
    brand: "ジェイゾロフト®",
    mechanism: "セロトニン再取り込み抑制（SSRI）",
    halfLifeText: "24時間",
    washoutMid: {
      display: "休薬必須でない（休薬検討時は5日）",
      hours: 0,
      note: "一律の休薬を支持するエビデンスなし。休薬を検討する場合は5日間を目安とするが、精神症状悪化リスクに十分配慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "paroxetine",
    category: "antiplatelet",
    name: "パロキセチン",
    brand: "パキシル®",
    mechanism: "セロトニン再取り込み抑制（SSRI）",
    halfLifeText: "21時間",
    washoutMid: {
      display: "休薬必須でない（休薬検討時は5日）",
      hours: 0,
      note: "一律の休薬を支持するエビデンスなし。休薬を検討する場合は5日間を目安とするが、精神症状悪化リスクに十分配慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "fluvoxamine",
    category: "antiplatelet",
    name: "フルボキサミン",
    brand: "ルボックス®／デプロメール®",
    mechanism: "セロトニン再取り込み抑制（SSRI）",
    halfLifeText: "16〜26時間",
    washoutMid: {
      display: "休薬必須でない（休薬検討時は5日）",
      hours: 0,
      note: "一律の休薬を支持するエビデンスなし。休薬を検討する場合は5日間を目安とするが、精神症状悪化リスクに十分配慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },

  // ============ 抗凝固薬 ============
  {
    id: "ufh",
    category: "anticoagulant",
    name: "未分画ヘパリン",
    brand: "ヘパリン®／カプロシン®",
    mechanism: "トロンビン・第Xa因子阻害",
    halfLifeText: "静注 0.7〜2時間／皮下注 2〜4時間",
    specialInput: "heparin-route",
    washoutByRoute: {
      iv: { display: "4時間（静脈内投与）", hours: 4 },
      sc: { display: "8〜10時間（皮下投与）", hours: 10 },
    },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
    generalNote: "穿刺手技前にAPTTおよび血小板数が基準値内であることを確認してください。",
  },
  {
    id: "enoxaparin",
    category: "anticoagulant",
    name: "エノキサパリン",
    brand: "クレキサン®",
    mechanism: "第Xa因子＞トロンビン阻害（低分子ヘパリン）",
    halfLifeText: "3〜6時間（皮下）",
    washoutMid: {
      display: "12時間",
      hours: 12,
      note: "CrCl＜30 mL/minでは半減期が延長するため、24時間への延長を考慮。",
    },
    washoutLow: { display: "12時間", hours: 12 },
    catheterRestart: { display: "抜去4時間後より", hours: 4 },
  },
  {
    id: "dalteparin",
    category: "anticoagulant",
    name: "ダルテパリン",
    brand: "フラグミン®",
    mechanism: "第Xa因子＞トロンビン阻害（低分子ヘパリン）",
    halfLifeText: "2〜4時間",
    washoutMid: { display: "12時間", hours: 12 },
    washoutLow: { display: "12時間", hours: 12 },
    catheterRestart: { display: "抜去4時間後より", hours: 4 },
    generalNote:
      "本邦では深部静脈血栓症予防の保険適応はなく、主にDICや体外循環回路の凝血防止目的での使用です。",
  },
  {
    id: "fondaparinux",
    category: "anticoagulant",
    name: "フォンダパリヌクス",
    brand: "アリクストラ®",
    mechanism: "第Xa因子阻害",
    halfLifeText: "17〜20時間（皮下）",
    washoutMid: {
      display: "36時間",
      hours: 36,
      note: "CrCl＜50 mL/minでは半減期が延長するため、72時間への延長を考慮。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
  },
  {
    id: "warfarin",
    category: "anticoagulant",
    name: "ワルファリン",
    brand: "ワーファリン®",
    mechanism: "ビタミンK依存性凝固因子合成阻害",
    halfLifeText: "4〜5日（投与量により個人差が大きい）",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "穿刺手技前にPT-INR ≦ 1.2であることを確認してください。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: {
      display: "抜去直後より（止血確認のうえで再開）",
      hours: 0,
    },
  },
  {
    id: "rivaroxaban",
    category: "anticoagulant",
    name: "リバーロキサバン",
    brand: "イグザレルト®",
    mechanism: "第Xa因子阻害（DOAC）",
    halfLifeText: "6〜9時間",
    specialInput: "doac-dose",
    doseLabels: {
      low: "低用量（10 mg×1回/日）",
      high: "標準・高用量（15 mg×1〜2回/日）",
    },
    washoutByDose: {
      low: { display: "24時間（低用量）", hours: 24 },
      high: { display: "72時間（標準・高用量）", hours: 72 },
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestartByDose: {
      low: { display: "抜去6時間後より（低用量）", hours: 6 },
      high: { display: "抜去24時間後より（標準・高用量）", hours: 24 },
    },
    generalNote: "腎機能障害（CrCl＜15 mL/min）では半減期が延長するため、72時間への延長や施行中止を考慮。",
  },
  {
    id: "apixaban",
    category: "anticoagulant",
    name: "アピキサバン",
    brand: "エリキュース®",
    mechanism: "第Xa因子阻害（DOAC）",
    halfLifeText: "8〜10時間",
    specialInput: "doac-dose",
    doseLabels: {
      low: "低用量（2.5 mg×2回/日）",
      high: "標準・高用量（5〜10 mg×2回/日）",
    },
    washoutByDose: {
      low: { display: "24時間（低用量）", hours: 24 },
      high: { display: "72時間（標準・高用量）", hours: 72 },
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestartByDose: {
      low: { display: "抜去6時間後より（低用量）", hours: 6 },
      high: { display: "抜去24時間後より（標準・高用量）", hours: 24 },
    },
    generalNote: "腎機能障害（CrCl＜15 mL/min）では半減期が延長するため、72時間への延長や施行中止を考慮。",
  },
  {
    id: "edoxaban",
    category: "anticoagulant",
    name: "エドキサバン",
    brand: "リクシアナ®",
    mechanism: "第Xa因子阻害（DOAC）",
    halfLifeText: "6〜9時間",
    specialInput: "doac-dose",
    doseLabels: {
      low: "低用量（15 mg×1回/日）",
      high: "標準・高用量（30〜60 mg×1回/日）",
    },
    washoutByDose: {
      low: { display: "24時間（低用量）", hours: 24 },
      high: { display: "72時間（標準・高用量）", hours: 72 },
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestartByDose: {
      low: { display: "抜去6時間後より（低用量）", hours: 6 },
      high: { display: "抜去24時間後より（標準・高用量）", hours: 24 },
    },
    generalNote: "腎機能障害（CrCl＜30 mL/min）では半減期が延長するため、72時間への延長や施行中止を考慮。",
  },
  {
    id: "dabigatran",
    category: "anticoagulant",
    name: "ダビガトラン",
    brand: "プラザキサ®",
    mechanism: "トロンビン阻害（DOAC）",
    halfLifeText: "11〜14時間（腎排泄率80%）",
    specialInput: "doac-dose",
    doseLabels: {
      low: "低用量（110 mg×2回/日）",
      high: "標準用量（150 mg×2回/日）",
    },
    washoutByDose: {
      low: { display: "48時間（低用量）", hours: 48 },
      high: { display: "72時間（標準用量）", hours: 72 },
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestartByDose: {
      low: { display: "抜去6時間後より（低用量）", hours: 6 },
      high: { display: "抜去24時間後より（標準用量）", hours: 24 },
    },
    generalNote:
      "腎排泄率が高い（80%）ため、CrCl＜30 mL/minでは休薬期間の延長（72時間）や施行中止を考慮。硬膜外カテーテル留置中の投与は推奨されていない（添付文書）。",
  },
];

export const CATEGORY_LABELS = {
  antiplatelet: "抗血小板薬・関連薬",
  anticoagulant: "抗凝固薬",
};
