// データソース:
// 「抗血栓療法中の区域麻酔・神経ブロックガイドライン」
// 日本ペインクリニック学会・日本麻酔科学会・日本区域麻酔学会 合同
// 2016年9月 表5（出血リスク分類）・表6（抗血小板薬等）・表7（抗凝固薬）

export const DEEP_BLOCKS = [
  "深頸神経叢ブロック",
  "頸部神経根ブロック",
  "頸部椎間関節ブロック",
  "三叉神経節ブロック",
  "舌咽神経ブロック",
  "翼口蓋神経節ブロック",
  "上顎神経ブロック",
  "下顎神経ブロック",
  "星状神経節ブロック（SGB）",
  "傍脊椎ブロック",
  "腕神経叢ブロック（斜角筋間法・鎖骨上法・鎖骨下法）",
  "内臓神経ブロック",
  "腰部交感神経節ブロック",
  "腰神経叢ブロック",
  "閉鎖神経ブロック",
  "坐骨神経ブロック",
];

export const SUPERFICIAL_BLOCKS = [
  "浅頸神経叢ブロック",
  "眼窩上神経ブロック",
  "後頭神経ブロック",
  "腕神経叢ブロック（腋窩法）",
  "前腕の神経ブロック",
  "肩甲上神経ブロック",
  "肋間神経ブロック",
  "腹直筋鞘ブロック",
  "腹横筋膜面ブロック（TAPブロックなど）",
  "大腿神経ブロック",
  "外側大腿皮神経ブロック",
  "伏在神経ブロック",
  "下腿の神経ブロック",
];

export const DRUGS = [
  // ============ 抗血小板薬等（表6） ============
  {
    id: "aspirin",
    category: "antiplatelet",
    name: "アスピリン",
    brand: "バイアスピリン®ほか",
    mechanism: "トロンボキサンA2合成阻害（不可逆的）",
    halfLifeText: "約2時間（血小板寿命に相当する7〜10日間、作用が持続）",
    washoutMid: {
      display: "症例ごとに判断（一律の休薬期間設定なし）",
      tbd: true,
      note:
        "施行する手技の出血リスクにより異なるため症例ごとに決定するとされています。高出血リスク手技では7日（二次予防など休薬リスクが高い場合は5日への短縮も考慮）が目安です。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: {
      display: "術後早期より再開可",
      hours: null,
      note: "カテーテル抜去時期というより、周術期の止血状況を踏まえて再開を判断します。",
    },
  },
  {
    id: "diclofenac",
    category: "antiplatelet",
    name: "ジクロフェナク",
    brand: "ボルタレン®",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "1〜2時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "indomethacin",
    category: "antiplatelet",
    name: "インドメタシン",
    brand: "インダシン®",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "5〜10時間",
    washoutMid: { display: "2日", days: 2 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "ibuprofen",
    category: "antiplatelet",
    name: "イブプロフェン",
    brand: "ブルフェン®ほか",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "2〜4時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "flurbiprofen",
    category: "antiplatelet",
    name: "フルルビプロフェン",
    brand: "ロピオン®",
    mechanism: "COX阻害（可逆的）",
    halfLifeText: "6時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "celecoxib",
    category: "antiplatelet",
    name: "セレコキシブ",
    brand: "セレコックス®",
    mechanism: "COX-2選択的阻害",
    halfLifeText: "5〜9時間",
    washoutMid: {
      display: "休薬不要",
      days: 0,
      note: "血小板凝集を直接阻害する作用はないとされています。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "休薬の必要なし", hours: 0 },
  },
  {
    id: "clopidogrel",
    category: "antiplatelet",
    name: "クロピドグレル",
    brand: "プラビックス®",
    mechanism: "P2Y12受容体遮断（不可逆的）",
    halfLifeText: "0.5〜3時間（作用は血小板寿命相当で持続）",
    washoutMid: {
      display: "7日（5日）",
      days: 7,
      note: "冠動脈ステント留置例など血栓リスクが高い場合は5日への短縮も考慮されます。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "ticlopidine",
    category: "antiplatelet",
    name: "チクロピジン",
    brand: "パナルジン®",
    mechanism: "アデニル酸シクラーゼ活性化＋P2Y12受容体遮断",
    halfLifeText: "1.5時間（作用は血小板寿命相当で持続）",
    washoutMid: {
      display: "7〜10日（5日）",
      days: 10,
      note: "状況により5日への短縮も考慮されます。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "prasugrel",
    category: "antiplatelet",
    name: "プラスグレル",
    brand: "エフィエント®",
    mechanism: "P2Y12受容体遮断（不可逆的）",
    halfLifeText: "5時間（作用は血小板寿命相当で持続）",
    washoutMid: {
      display: "7〜10日（5日）",
      days: 10,
      note: "状況により5日への短縮も考慮されます。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "cilostazol",
    category: "antiplatelet",
    name: "シロスタゾール",
    brand: "プレタール®",
    mechanism: "ホスホジエステラーゼ阻害",
    halfLifeText: "11〜13時間",
    washoutMid: {
      display: "2日",
      days: 2,
      note: "アスピリンと併用中の場合はアスピリンの休薬基準に従います。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "dipyridamole",
    category: "antiplatelet",
    name: "ジピリダモール",
    brand: "ペルサンチン®",
    mechanism: "ホスホジエステラーゼ阻害",
    halfLifeText: "10時間",
    washoutMid: { display: "2日", days: 2 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "epa",
    category: "antiplatelet",
    name: "イコサペント酸エチル",
    brand: "エパデール®",
    mechanism: "トロンボキサンA2阻害",
    halfLifeText: "60〜65時間",
    washoutMid: { display: "7〜10日", days: 10 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "omega3-epa-dha",
    category: "antiplatelet",
    name: "オメガ-3脂肪酸エチル（EPA・DHA配合）",
    brand: "ロトリガ®",
    mechanism: "トロンボキサンA2産生抑制等による抗血小板作用（EPA＋DHA配合製剤）",
    halfLifeText:
      "明確な血中半減期の設定なし。EPA・DHAは血小板膜リン脂質に取り込まれ、効果は血小板の入れ替わる期間（7〜10日程度）持続するとされています。",
    washoutMid: {
      display: "7〜10日",
      days: 10,
      note: "本剤（EPA＋DHA配合）はガイドライン本表に個別記載がないため、同じ抗血小板機序を持つイコサペント酸エチル（エパデール®）に準じた休薬目安を表示しています。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
    generalNote:
      "ガイドライン本表に記載のない薬剤のため、エパデール®の基準を準用した参考値です。実際の判断は施設プロトコル・主治医の判断によってください。",
  },
  {
    id: "sarpogrelate",
    category: "antiplatelet",
    name: "サルポグレラート",
    brand: "アンプラーグ®",
    mechanism: "5-HT2受容体遮断",
    halfLifeText: "0.8時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "beraprost",
    category: "antiplatelet",
    name: "ベラプロスト",
    brand: "ドルナー®／プロサイリン®",
    mechanism: "アデニル酸シクラーゼ活性化",
    halfLifeText: "0.5〜0.7時間",
    washoutMid: { display: "1日", days: 1 },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "limaprost",
    category: "antiplatelet",
    name: "リマプロストアルファデクス",
    brand: "オパルモン®／プロレナール®",
    mechanism:
      "プロスタグランジンE1（PGE1）誘導体。血小板cAMP増加・トロンボキサンA2産生抑制による血小板凝集抑制作用（作用の強さはPGI2に匹敵するとされる）",
    halfLifeText: "約0.5時間（添付文書記載の消失半減期：0.5〜1時間）",
    washoutMid: {
      display: "1日",
      days: 1,
      note: "ガイドライン本表に個別記載がないため、同様の機序・半減期を持つベラプロスト等のプロスタグランジン系抗血小板薬に準じた休薬目安を表示しています。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
    generalNote:
      "ガイドライン本表に記載のない薬剤のため、同種同効薬（ベラプロスト等）の基準を準用した参考値です。実際の判断は施設プロトコル・主治医の判断によってください。",
  },
  {
    id: "clomipramine",
    category: "antiplatelet",
    name: "クロミプラミン",
    brand: "アナフラニール®",
    mechanism: "セロトニン再取り込み抑制（三環系）",
    halfLifeText: "24時間",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "周術期の抗うつ薬休薬は原疾患の悪化リスクがあるため、リスク・ベネフィットを慎重に判断してください。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "sertraline",
    category: "antiplatelet",
    name: "セルトラリン",
    brand: "ジェイゾロフト®",
    mechanism: "セロトニン再取り込み抑制（SSRI）",
    halfLifeText: "24時間",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "周術期の抗うつ薬休薬は原疾患の悪化リスクがあるため、リスク・ベネフィットを慎重に判断してください。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "paroxetine",
    category: "antiplatelet",
    name: "パロキセチン",
    brand: "パキシル®",
    mechanism: "セロトニン再取り込み抑制（SSRI）",
    halfLifeText: "21時間",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "周術期の抗うつ薬休薬は原疾患の悪化リスクがあるため、リスク・ベネフィットを慎重に判断してください。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },
  {
    id: "fluvoxamine",
    category: "antiplatelet",
    name: "フルボキサミン",
    brand: "ルボックス®／デプロメール®",
    mechanism: "セロトニン再取り込み抑制（SSRI）",
    halfLifeText: "16〜26時間",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "周術期の抗うつ薬休薬は原疾患の悪化リスクがあるため、リスク・ベネフィットを慎重に判断してください。",
    },
    washoutLow: { display: "休薬不要", days: 0 },
    catheterRestart: { display: "抜去後より", hours: 0 },
  },

  // ============ 抗凝固薬（表7） ============
  {
    id: "ufh",
    category: "anticoagulant",
    name: "未分画ヘパリン",
    brand: "ヘパリン®／カプロシン®",
    mechanism: "トロンビン・第Xa因子阻害",
    halfLifeText: "静注 0.7〜2時間／皮下注 2〜4時間",
    specialInput: "heparin-route",
    washoutByRoute: {
      iv: { display: "4時間（静脈内投与）", hours: 4 },
      sc: { display: "8〜10時間（皮下投与）", hours: 10 },
    },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
    generalNote: "穿刺手技前にAPTTおよび血小板数が基準値内であることを確認してください。",
  },
  {
    id: "enoxaparin",
    category: "anticoagulant",
    name: "エノキサパリン",
    brand: "クレキサン®",
    mechanism: "第Xa因子＞トロンビン阻害（低分子ヘパリン）",
    halfLifeText: "3〜6時間（皮下）",
    washoutMid: { display: "12時間", hours: 12 },
    washoutLow: { display: "12時間", hours: 12 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
  },
  {
    id: "dalteparin",
    category: "anticoagulant",
    name: "ダルテパリン",
    brand: "フラグミン®",
    mechanism: "第Xa因子＞トロンビン阻害（低分子ヘパリン）",
    halfLifeText: "2〜4時間",
    washoutMid: { display: "12時間", hours: 12 },
    washoutLow: { display: "12時間", hours: 12 },
    catheterRestart: { display: "抜去2時間後より", hours: 2 },
    generalNote:
      "本邦では深部静脈血栓症予防の保険適応はなく、主にDICや体外循環回路の凝血防止目的での使用です。",
  },
  {
    id: "fondaparinux",
    category: "anticoagulant",
    name: "フォンダパリヌクス",
    brand: "アリクストラ®",
    mechanism: "第Xa因子阻害",
    halfLifeText: "17〜20時間（皮下）",
    washoutMid: { display: "4日", days: 4 },
    washoutLow: {
      display: "個別判断（休薬する場合は半減期の約2倍が目安）",
      tbd: true,
    },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
  },
  {
    id: "warfarin",
    category: "anticoagulant",
    name: "ワルファリン",
    brand: "ワーファリン®",
    mechanism: "ビタミンK依存性凝固因子合成阻害",
    halfLifeText: "4〜5日（投与量により個人差が大きい）",
    washoutMid: {
      display: "5日",
      days: 5,
      note: "穿刺手技前にPT-INR ≦ 1.2であることを確認してください。",
    },
    washoutLow: {
      display: "個別判断（休薬する場合は半減期の約2倍が目安）",
      tbd: true,
    },
    catheterRestart: {
      display: "抜去後、止血確認のうえで再開（具体的な時間設定の規定なし）",
      hours: null,
    },
  },
  {
    id: "dabigatran",
    category: "anticoagulant",
    name: "ダビガトラン",
    brand: "プラザキサ®",
    mechanism: "トロンビン阻害",
    halfLifeText: "CrCl≥60: 約14時間／30<CrCl<60: 約18時間",
    specialInput: "dabigatran-renal",
    washoutMidByRenal: {
      normal: { display: "4日（CrCl≥60 mL/min）", days: 4 },
      low: { display: "5日（30<CrCl<60 mL/min）", days: 5 },
    },
    washoutLow: {
      display: "個別判断（休薬する場合は半減期の約2倍が目安）",
      tbd: true,
    },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
    generalNote:
      "硬膜外カテーテル留置中の患者への投与は推奨されていません（添付文書）。",
  },
  {
    id: "rivaroxaban",
    category: "anticoagulant",
    name: "リバーロキサバン",
    brand: "イグザレルト®",
    mechanism: "第Xa因子阻害",
    halfLifeText: "5〜9時間",
    washoutMid: { display: "2日", days: 2 },
    washoutLow: {
      display: "個別判断（休薬する場合は半減期の約2倍が目安）",
      tbd: true,
    },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
  },
  {
    id: "apixaban",
    category: "anticoagulant",
    name: "アピキサバン",
    brand: "エリキュース®",
    mechanism: "第Xa因子阻害",
    halfLifeText: "8〜15時間",
    washoutMid: { display: "3日", days: 3 },
    washoutLow: {
      display: "個別判断（休薬する場合は半減期の約2倍が目安）",
      tbd: true,
    },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
  },
  {
    id: "edoxaban",
    category: "anticoagulant",
    name: "エドキサバン",
    brand: "リクシアナ®",
    mechanism: "第Xa因子阻害",
    halfLifeText: "6〜11時間",
    washoutMid: { display: "2日", days: 2 },
    washoutLow: {
      display: "個別判断（休薬する場合は半減期の約2倍が目安）",
      tbd: true,
    },
    catheterRestart: { display: "抜去6時間後より", hours: 6 },
  },
];

export const CATEGORY_LABELS = {
  antiplatelet: "抗血小板薬・関連薬",
  anticoagulant: "抗凝固薬",
};
